name: Docker Push (V7)

on:
  push:
    tags:
      - v7
      - v7.*

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag elliottpope/cloudfoundry-cli-action:v7
    - name: Get Version
      id: get_version
      run: |
        VERSION=$(docker run --entrypoint "/bin/bash" elliottpope/cloudfoundry-cli-action:v7 -c cf --version | sed -nr 's/^cf version ([0-9]\.[0-9]+\.[0-9]+).*/\1/p' | xargs)
        echo "CF CLI Version is ${VERSION}"
        echo "::set-output name=version::$(echo ${VERSION})"
    - name: Tag Docker Image
      run: docker tag elliottpope/cloudfoundry-cli-action:v7 elliottpope/cloudfoundry-cli-action:${{ steps.get_version.outputs.version }}
    - name: Push Docker Image
      run: docker push -a elliottpope/cloudfoundry-cli-action:v7
